chore: update latest dependencies
trustbloc/edv pull request #205
Opened 2021-03-09 20:32 UTC by Baha-sk

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

2021-03-09 20:33 UTC, rolsonquadras approved these changes

2021-03-09 20:33 UTC, DRK3 approved these changes

2021-03-09 20:35 UTC, fqutishat requested changes
@Baha-sk do we need to change this https://github.com/trustbloc/edv/blob/main/pkg/auth/zcapld/service.go#L118

2021-03-09 22:17 UTC, fqutishat approved these changes

2021-03-10 15:37 UTC, Baha-sk commented
> @Baha-sk do we need to change this https://github.com/trustbloc/edv/blob/main/pkg/auth/zcapld/service.go#L118

@fqutishat as long as we create the loader using `verifiable.CachingJSONLDLoader()` here:
https://github.com/trustbloc/edv/blob/main/cmd/edv-rest/startcmd/start.go#L623

Nothing else needs to be changed. The edv service creation and handler setup (including the line you mentioned above) is instantiated during the start of the edv-rest command.

AFG has been updated to load the framework's cache document loader in `verifiable.CachingJSONLDLoader()`.

2021-03-10 15:37 UTC, merged